source 'https://rubygems.org'
#
gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

group :development, :test do
  gem 'sqlite3'
end
group :production do
  gem 'pg'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'better_errors'
  gem 'sunspot_solr'  # optional pre-packaged Solr distribution for use in development
  gem 'faker'
  gem 'populator'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

#Search functionality
gem 'sunspot_rails'

# To use debugger
# gem 'debugger'

#User Authentication
gem 'devise'

#private messaging
gem 'mailboxer'

#bootstrap
gem "therubyracer"
gem 'bootstrap-sass'

#haml
#gem 'haml-rails', '>= 0.3.4', :group => :development

#image upload
gem "paperclip", "~> 4.3"

#form helper
gem 'bootstrap_form'
#gem 'formtastic'
#gem 'simple_form'

#pagination
gem 'kaminari'

gem "haml-rails"
gem 'simple_form'

gem 'acts-as-taggable-on'

gem 'aws-sdk'
gem 'mandrill-api'
gem 'json'
#web server for heroku
gem 'unicorn'

#get data from 3taps
gem 'httparty'